-- 001_initial_schema.sql
-- MARS: Multilingual Adaptive Report Studio — initial schema

-- Supported locales (EU official languages)
CREATE TABLE IF NOT EXISTS locales (
    code        TEXT PRIMARY KEY,                  -- BCP-47 language code, e.g. 'en', 'de'
    name        TEXT NOT NULL,                     -- English name of the language
    native_name TEXT NOT NULL,                     -- Name in the language itself
    is_active   INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- Per-client locale settings
CREATE TABLE IF NOT EXISTS client_locale_settings (
    client_id        TEXT NOT NULL,
    primary_locale   TEXT NOT NULL REFERENCES locales(code),
    enabled_locales  TEXT NOT NULL DEFAULT '[]',   -- JSON array of locale codes
    fallback_locale  TEXT NOT NULL DEFAULT 'en' REFERENCES locales(code),
    updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    PRIMARY KEY (client_id)
);

-- Industry profile templates
CREATE TABLE IF NOT EXISTS industry_profiles (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT NOT NULL UNIQUE,              -- e.g. 'eu_food_manufacturer'
    description TEXT,
    config_json TEXT NOT NULL DEFAULT '{}',        -- JSON with default sources, keywords
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- Keyword rules per client
CREATE TABLE IF NOT EXISTS keyword_rules (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id   TEXT NOT NULL,
    phrase      TEXT NOT NULL,
    locale      TEXT NOT NULL DEFAULT 'en' REFERENCES locales(code),
    weight      REAL NOT NULL DEFAULT 1.0,
    category    TEXT,
    is_active   INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    UNIQUE (client_id, phrase, locale)
);

CREATE INDEX IF NOT EXISTS idx_keyword_rules_client ON keyword_rules(client_id);

-- Source proposals generated by agents
CREATE TABLE IF NOT EXISTS source_proposals (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id     TEXT NOT NULL,
    url           TEXT NOT NULL,
    title         TEXT,
    publisher     TEXT,
    rationale     TEXT,
    status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'approved', 'rejected', 'paused')),
    proposed_by   TEXT NOT NULL DEFAULT 'source-scout',
    reviewed_by   TEXT,
    reviewed_at   TEXT,
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_source_proposals_client ON source_proposals(client_id);
CREATE INDEX IF NOT EXISTS idx_source_proposals_status ON source_proposals(status);

-- Report templates (master definitions)
CREATE TABLE IF NOT EXISTS report_templates (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT NOT NULL,
    description     TEXT,
    industry_profile_id INTEGER REFERENCES industry_profiles(id),
    base_locale     TEXT NOT NULL DEFAULT 'en' REFERENCES locales(code),
    current_version INTEGER NOT NULL DEFAULT 1,
    is_published    INTEGER NOT NULL DEFAULT 0,
    created_by      TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- Immutable template version snapshots (new version = new row)
CREATE TABLE IF NOT EXISTS template_versions (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    template_id     INTEGER NOT NULL REFERENCES report_templates(id),
    version_number  INTEGER NOT NULL,
    sections_json   TEXT NOT NULL DEFAULT '[]',    -- JSON array of section definitions
    theme_tokens    TEXT NOT NULL DEFAULT '{}',    -- JSON object with design tokens
    changelog_note  TEXT,
    created_by      TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    UNIQUE (template_id, version_number)
);

CREATE INDEX IF NOT EXISTS idx_template_versions_template ON template_versions(template_id);

-- Per-client overrides on top of a template version
CREATE TABLE IF NOT EXISTS client_template_overrides (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id           TEXT NOT NULL,
    template_version_id INTEGER NOT NULL REFERENCES template_versions(id),
    overrides_json      TEXT NOT NULL DEFAULT '{}', -- JSON patch on top of template
    is_active           INTEGER NOT NULL DEFAULT 1,
    created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    UNIQUE (client_id, template_version_id)
);

CREATE INDEX IF NOT EXISTS idx_client_template_overrides_client ON client_template_overrides(client_id);

-- Report drafts
CREATE TABLE IF NOT EXISTS report_drafts (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id           TEXT NOT NULL,
    template_version_id INTEGER REFERENCES template_versions(id),
    title               TEXT NOT NULL,
    period              TEXT,                        -- e.g. '2026-02' or 'Q1-2026'
    primary_locale      TEXT NOT NULL DEFAULT 'en' REFERENCES locales(code),
    status              TEXT NOT NULL DEFAULT 'composing'
                        CHECK (status IN (
                            'composing', 'review', 'revision',
                            'translating', 'approval', 'approved',
                            'exported', 'archived'
                        )),
    current_revision_id INTEGER,                     -- FK set after first revision inserted
    created_by          TEXT,
    created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_report_drafts_client ON report_drafts(client_id);
CREATE INDEX IF NOT EXISTS idx_report_drafts_status ON report_drafts(status);

-- Revision snapshots for each draft (full snapshot per revision, not diffs)
CREATE TABLE IF NOT EXISTS draft_revisions (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    draft_id      INTEGER NOT NULL REFERENCES report_drafts(id),
    revision_number INTEGER NOT NULL,
    sections_json TEXT NOT NULL DEFAULT '[]',        -- full snapshot of all sections
    authored_by   TEXT,
    note          TEXT,
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    UNIQUE (draft_id, revision_number)
);

CREATE INDEX IF NOT EXISTS idx_draft_revisions_draft ON draft_revisions(draft_id);

-- Chat messages attached to a draft (section-level or draft-level)
CREATE TABLE IF NOT EXISTS draft_chat_messages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    draft_id    INTEGER NOT NULL REFERENCES report_drafts(id),
    section_id  TEXT,                               -- NULL = draft-level message
    role        TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content     TEXT NOT NULL,
    revision_id INTEGER REFERENCES draft_revisions(id),
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_draft_chat_messages_draft ON draft_chat_messages(draft_id);
CREATE INDEX IF NOT EXISTS idx_draft_chat_messages_section ON draft_chat_messages(draft_id, section_id);

-- Per-section approval states (not per-draft)
CREATE TABLE IF NOT EXISTS approval_states (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    draft_id    INTEGER NOT NULL REFERENCES report_drafts(id),
    section_id  TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'approved', 'rejected', 'needs_revision')),
    reviewer    TEXT,
    comment     TEXT,
    revision_id INTEGER REFERENCES draft_revisions(id),
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    UNIQUE (draft_id, section_id)
);

CREATE INDEX IF NOT EXISTS idx_approval_states_draft ON approval_states(draft_id);
CREATE INDEX IF NOT EXISTS idx_approval_states_draft_section ON approval_states(draft_id, section_id);

-- Export jobs (PDF or DOCX generation)
CREATE TABLE IF NOT EXISTS export_jobs (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    draft_id    INTEGER NOT NULL REFERENCES report_drafts(id),
    revision_id INTEGER REFERENCES draft_revisions(id),
    format      TEXT NOT NULL CHECK (format IN ('pdf', 'docx')),
    locale      TEXT REFERENCES locales(code),
    status      TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    output_path TEXT,
    error       TEXT,
    requested_by TEXT,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_export_jobs_draft ON export_jobs(draft_id);
CREATE INDEX IF NOT EXISTS idx_export_jobs_status ON export_jobs(status);
