"""
Seed evidence records for all clients using SourceScoutAgent.
Run from project root: .venv/bin/python scripts/seed_evidence.py
"""
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from agents.source_scout import SourceScoutAgent


SEEDS = {
    "gerold-foods": [
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022L2464",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSRD — Corporate Sustainability Reporting Directive 2022/2464",
            "snippet": "Large undertakings and listed SMEs must report sustainability information under ESRS standards.",
            "topic": "ghg",
            "related_regulation_id": "CSRD-2022",
            "confidence": 0.98,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024L1760",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSDDD — Corporate Sustainability Due Diligence Directive 2024/1760",
            "snippet": "Companies must conduct human rights and environmental due diligence across their value chains.",
            "topic": "social_human_rights",
            "related_regulation_id": "CSDDD-2024",
            "confidence": 0.97,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32025R0040",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "PPWR — Packaging and Packaging Waste Regulation 2025/40",
            "snippet": "Mandatory recycled content targets and packaging minimisation requirements from 2030.",
            "topic": "packaging",
            "related_regulation_id": "PPWR-2025",
            "confidence": 0.96,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R0956",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CBAM — Carbon Border Adjustment Mechanism Regulation 2023/956",
            "snippet": "Carbon price on imports of certain goods from countries without equivalent carbon pricing.",
            "topic": "ghg",
            "related_regulation_id": "CBAM-2023",
            "confidence": 0.95,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R1115",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "EUDR — EU Deforestation Regulation 2023/1115",
            "snippet": "Due diligence requirements for operators placing certain commodities on the EU market.",
            "topic": "waste",
            "related_regulation_id": "EUDR-2023",
            "confidence": 0.94,
        },
        {
            "url": "https://www.recht.bund.de/bgbl/1/2021/S2959/regelungstext.pdf",
            "source_id": "bgbl",
            "source_name": "Bundesgesetzblatt",
            "document_title": "LkSG — Lieferkettensorgfaltspflichtengesetz (Supply Chain Due Diligence Act)",
            "snippet": "German companies with 1,000+ employees must conduct human rights and environmental due diligence.",
            "topic": "social_human_rights",
            "related_regulation_id": "LkSG-2021",
            "confidence": 0.95,
        },
        {
            "url": "https://www.recht.bund.de/bgbl/1/2024/verpackdg-aenderung.html",
            "source_id": "bgbl",
            "source_name": "Bundesgesetzblatt",
            "document_title": "VerpackDG Amendment — Packaging Act Amendment 2024",
            "snippet": "Updated recyclability requirements and extended producer responsibility for packaging producers.",
            "topic": "packaging",
            "related_regulation_id": "VerpackDG-2024",
            "confidence": 0.88,
        },
        {
            "url": "https://www.bmuv.de/themen/ressourceneffizienz/nationales-ressourceneffizienzprogramm",
            "source_id": "bmuv",
            "source_name": "BMUV/UBA",
            "document_title": "Nationales Ressourceneffizienzprogramm (ProgRess III)",
            "snippet": "Germany's national resource efficiency strategy targets a 30% reduction in material footprint by 2030.",
            "topic": "waste",
            "related_regulation_id": "ProgRess-III",
            "confidence": 0.87,
        },
        {
            "url": "https://www.bmuv.de/themen/klimaschutz/klimaschutzgesetz",
            "source_id": "bmuv",
            "source_name": "BMUV/UBA",
            "document_title": "Bundes-Klimaschutzgesetz (KSG) — Federal Climate Protection Act",
            "snippet": "Germany's GHG reduction targets: 65% by 2030, 88% by 2040, climate neutrality by 2045.",
            "topic": "ghg",
            "related_regulation_id": "KSG-2021",
            "confidence": 0.96,
        },
        {
            "url": "https://www.bafa.de/DE/Themen/Aussenwirtschaft_Investitionskontrolle/Lieferkettensorgfaltspflichtengesetz/lksg_node.html",
            "source_id": "bafa",
            "source_name": "BAFA",
            "document_title": "BAFA LkSG Guidance and Compliance Framework",
            "snippet": "BAFA enforcement authority under LkSG; guidance on risk analysis and remediation measures.",
            "topic": "social_human_rights",
            "related_regulation_id": "LkSG-2021",
            "confidence": 0.90,
        },
        {
            "url": "https://www.bafa.de/DE/Themen/Aussenwirtschaft_Investitionskontrolle/Lieferkettensorgfaltspflichtengesetz/LkSG_Fragebogen/lksg_fragebogen_node.html",
            "source_id": "bafa",
            "source_name": "BAFA",
            "document_title": "BAFA LkSG Self-Assessment Questionnaire",
            "snippet": "Annual reporting questionnaire for companies subject to LkSG obligations.",
            "topic": "social_human_rights",
            "related_regulation_id": "LkSG-2021",
            "confidence": 0.88,
        },
        {
            "url": "https://www.zsvr.de/ZSVR/DE/Aufgaben/Verpackungsregister/LUCID/lucid_node.html",
            "source_id": "zsvr",
            "source_name": "ZSVR/LUCID",
            "document_title": "LUCID Verpackungsregister — Registration Requirements",
            "snippet": "All initial distributors of packaging must register in the LUCID packaging register.",
            "topic": "packaging",
            "related_regulation_id": "VerpackDG-2019",
            "confidence": 0.93,
        },
        {
            "url": "https://www.zsvr.de/ZSVR/DE/Aufgaben/Verpackungsregister/Gebuehren/gebuehren_node.html",
            "source_id": "zsvr",
            "source_name": "ZSVR/LUCID",
            "document_title": "LUCID Fee Schedule 2025",
            "snippet": "Updated fee schedule for LUCID registration and annual reporting obligations.",
            "topic": "packaging",
            "related_regulation_id": "VerpackDG-2019",
            "confidence": 0.90,
        },
        {
            "url": "https://www.umweltbundesamt.de/themen/wasser/gewaesser/grundwasser",
            "source_id": "bmuv",
            "source_name": "BMUV/UBA",
            "document_title": "UBA Groundwater Quality Standards — Industrial Discharge Limits",
            "snippet": "Updated nitrate and phosphate limits for industrial water users under WHG amendments.",
            "topic": "water",
            "related_regulation_id": "WHG-2023",
            "confidence": 0.85,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1233",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "ESRS Set 1 — European Sustainability Reporting Standards (Commission Delegated Regulation)",
            "snippet": "ESRS E1-E5 (climate, pollution, water, biodiversity, resource use) and S1-S4 (social) mandatory disclosure.",
            "topic": "ghg",
            "related_regulation_id": "CSRD-2022",
            "confidence": 0.97,
        },
    ],

    "alpine-dairy": [
        {
            "url": "https://www.fedlex.admin.ch/eli/cc/1986/208_208_208/de",
            "source_id": "fedlex",
            "source_name": "Fedlex",
            "document_title": "USG — Umweltschutzgesetz (Swiss Environmental Protection Act)",
            "snippet": "Swiss federal law on environmental protection, waste management and polluter liability.",
            "topic": "waste",
            "related_regulation_id": "USG-SR-814",
            "confidence": 0.96,
        },
        {
            "url": "https://www.fedlex.admin.ch/eli/cc/1986/1146_1146_1146/de",
            "source_id": "fedlex",
            "source_name": "Fedlex",
            "document_title": "VOCV — Ordinance on Volatile Organic Compounds",
            "snippet": "Swiss VOC emission limits for industrial and food processing operations.",
            "topic": "ghg",
            "related_regulation_id": "VOCV-SR-814",
            "confidence": 0.90,
        },
        {
            "url": "https://www.fedlex.admin.ch/eli/cc/2023/420/de",
            "source_id": "fedlex",
            "source_name": "Fedlex",
            "document_title": "Verpackungsverordnung CH — Swiss Packaging Ordinance 2023",
            "snippet": "Swiss equivalent to EU PPWR: recyclability targets and single-use plastic restrictions.",
            "topic": "packaging",
            "related_regulation_id": "VerpV-2023",
            "confidence": 0.88,
        },
        {
            "url": "https://www.bafu.admin.ch/bafu/de/home/themen/klima/fachinformationen/klimastrategie-2050.html",
            "source_id": "bafu",
            "source_name": "BAFU — Swiss Federal Office for the Environment",
            "document_title": "BAFU Climate Strategy 2050 — Long-term Net-Zero Pathway",
            "snippet": "Switzerland targets net-zero GHG emissions by 2050; interim milestones for industry sectors.",
            "topic": "ghg",
            "related_regulation_id": "CO2G-CH-2023",
            "confidence": 0.93,
        },
        {
            "url": "https://www.bafu.admin.ch/bafu/de/home/themen/wasser/fachinformationen/zustand-der-gewaesser/biologischer-zustand-der-gewaesser.html",
            "source_id": "bafu",
            "source_name": "BAFU — Swiss Federal Office for the Environment",
            "document_title": "BAFU Water Quality Monitoring — Swiss Waterbody Assessment 2025",
            "snippet": "Monitoring framework for waterbody ecological status; discharge permit requirements for dairy.",
            "topic": "water",
            "related_regulation_id": "GSchG-SR-814",
            "confidence": 0.87,
        },
        {
            "url": "https://www.uvek.admin.ch/uvek/de/home/uvek/medien/medienmitteilungen/anzeige.msg-id-92345.html",
            "source_id": "uvek",
            "source_name": "UVEK — Swiss Ministry of Environment",
            "document_title": "UVEK Net Zero Strategy for Industry — 2024 Update",
            "snippet": "Sector-specific decarbonisation pathways for food processing and dairy industry.",
            "topic": "ghg",
            "related_regulation_id": "CO2G-CH-2023",
            "confidence": 0.85,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022L2464",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSRD — Corporate Sustainability Reporting Directive (EU export relevance for CH)",
            "snippet": "Swiss exporters to EU must comply with CSRD requirements from EU business partners.",
            "topic": "ghg",
            "related_regulation_id": "CSRD-2022",
            "confidence": 0.94,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32025R0040",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "PPWR — Packaging and Packaging Waste Regulation (EU market access)",
            "snippet": "Swiss dairy exporters to EU must meet PPWR packaging requirements from 2028.",
            "topic": "packaging",
            "related_regulation_id": "PPWR-2025",
            "confidence": 0.93,
        },
        {
            "url": "https://www.fedlex.admin.ch/eli/cc/2021/846/de",
            "source_id": "fedlex",
            "source_name": "Fedlex",
            "document_title": "CO2-Gesetz CH — Swiss CO2 Act 2021 (revised)",
            "snippet": "Updated Swiss CO2 levy on fuels; ETS participation for large emitters; aviation surcharge.",
            "topic": "ghg",
            "related_regulation_id": "CO2G-CH-2021",
            "confidence": 0.95,
        },
        {
            "url": "https://www.bafu.admin.ch/bafu/de/home/themen/abfall/fachinformationen/abfallpolitik-der-schweiz/lebensmittelabfall.html",
            "source_id": "bafu",
            "source_name": "BAFU — Swiss Federal Office for the Environment",
            "document_title": "BAFU Food Waste Strategy — Swiss Action Plan 2025",
            "snippet": "Switzerland's national food waste reduction targets; mandatory reporting for food processors.",
            "topic": "waste",
            "related_regulation_id": "USG-SR-814",
            "confidence": 0.86,
        },
        {
            "url": "https://www.fedlex.admin.ch/eli/cc/1999/415/de",
            "source_id": "fedlex",
            "source_name": "Fedlex",
            "document_title": "GSchG — Gewässerschutzgesetz (Waters Protection Act)",
            "snippet": "Effluent standards for dairy wastewater; BOD limits and temperature restrictions.",
            "topic": "water",
            "related_regulation_id": "GSchG-SR-814",
            "confidence": 0.94,
        },
        {
            "url": "https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=20007045",
            "source_id": "ris",
            "source_name": "Rechtsinformationssystem Austria",
            "document_title": "Austrian Klimaschutzgesetz (KSG) — Climate Protection Act",
            "snippet": "Austrian climate targets aligned with EU Fit for 55; sector budgets for industry.",
            "topic": "ghg",
            "related_regulation_id": "AT-KSG-2011",
            "confidence": 0.89,
        },
    ],

    "nordic-harvest": [
        {
            "url": "https://lovdata.no/dokument/NL/lov/1981-03-13-6",
            "source_id": "lovdata",
            "source_name": "Lovdata",
            "document_title": "Forurensningsloven — Norwegian Pollution Control Act (amended 2023)",
            "snippet": "Updated discharge permits and emission limits for seafood processing facilities.",
            "topic": "water",
            "related_regulation_id": "Forurensningsloven-1981",
            "confidence": 0.95,
        },
        {
            "url": "https://lovdata.no/dokument/NL/lov/2021-06-18-99",
            "source_id": "lovdata",
            "source_name": "Lovdata",
            "document_title": "Åpenhetsloven — Norwegian Transparency Act 2021",
            "snippet": "Norwegian companies must conduct and publish human rights and decent work due diligence.",
            "topic": "social_human_rights",
            "related_regulation_id": "Aapenhetsloven-2021",
            "confidence": 0.97,
        },
        {
            "url": "https://lovdata.no/dokument/NL/lov/2008-06-06-37",
            "source_id": "lovdata",
            "source_name": "Lovdata",
            "document_title": "Havressurslova — Marine Resources Act (fisheries quota management)",
            "snippet": "Sustainability requirements for commercial fishing; quota systems and bycatch limits.",
            "topic": "waste",
            "related_regulation_id": "Havressurslova-2008",
            "confidence": 0.91,
        },
        {
            "url": "https://lovdata.no/dokument/NL/lov/2017-06-16-63",
            "source_id": "lovdata",
            "source_name": "Lovdata",
            "document_title": "Klimaloven — Norwegian Climate Change Act",
            "snippet": "Norway's binding 2030 target: 55% GHG reduction vs 1990; annual reporting to Parliament.",
            "topic": "ghg",
            "related_regulation_id": "Klimaloven-2017",
            "confidence": 0.96,
        },
        {
            "url": "https://www.miljodirektoratet.no/ansvarsomraader/industri-og-naeringsliv/utslippstillatelse/",
            "source_id": "miljodirektoratet",
            "source_name": "Norwegian Environment Agency",
            "document_title": "Miljødirektoratet — Discharge Permit Requirements for Fish Processing",
            "snippet": "Fish processing plants require individual discharge permits; effluent BOD and nutrient limits.",
            "topic": "water",
            "related_regulation_id": "Forurensningsloven-1981",
            "confidence": 0.90,
        },
        {
            "url": "https://www.miljodirektoratet.no/ansvarsomraader/klima/norges-klimamaal/",
            "source_id": "miljodirektoratet",
            "source_name": "Norwegian Environment Agency",
            "document_title": "Norway GHG Monitoring and Reporting Framework 2025",
            "snippet": "Updated GHG inventory methodology; mandatory carbon footprint reporting for food exporters.",
            "topic": "ghg",
            "related_regulation_id": "Klimaloven-2017",
            "confidence": 0.88,
        },
        {
            "url": "https://www.stortinget.no/no/Saker-og-publikasjoner/Publikasjoner/Innstillinger/Stortinget/2024-2025/inns-202425-253s/",
            "source_id": "stortinget",
            "source_name": "Stortinget — Norwegian Parliament",
            "document_title": "Stortinget Prop. L — Carbon Tax Increase 2025 (NOK 952/tCO2)",
            "snippet": "Norwegian carbon tax raised to NOK 952/tCO2 from 2025; fisheries sector partial exemption.",
            "topic": "ghg",
            "related_regulation_id": "CO2-avgift-NO-2025",
            "confidence": 0.92,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022L2464",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSRD — EEA Relevance for Norwegian Exporters",
            "snippet": "Norway as EEA member must implement CSRD; Norwegian companies exporting to EU affected.",
            "topic": "ghg",
            "related_regulation_id": "CSRD-2022",
            "confidence": 0.93,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R1115",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "EUDR — EU Deforestation Regulation (EEA-relevant for Norwegian seafood)",
            "snippet": "Norwegian seafood operators exporting to EU must provide EUDR due diligence statements.",
            "topic": "social_human_rights",
            "related_regulation_id": "EUDR-2023",
            "confidence": 0.87,
        },
        {
            "url": "https://lovdata.no/dokument/NL/lov/2018-06-22-83",
            "source_id": "lovdata",
            "source_name": "Lovdata",
            "document_title": "Plastforurensningsloven — Plastic Pollution Prevention Act 2018 (amended 2024)",
            "snippet": "Extended producer responsibility for plastic packaging; mandatory take-back schemes.",
            "topic": "packaging",
            "related_regulation_id": "Plastforurensningsloven-2018",
            "confidence": 0.89,
        },
        {
            "url": "https://www.miljodirektoratet.no/ansvarsomraader/avfall/emballasjeavfall/",
            "source_id": "miljodirektoratet",
            "source_name": "Norwegian Environment Agency",
            "document_title": "Miljødirektoratet Packaging Waste Guidance 2025",
            "snippet": "Collection and recycling targets for packaging: 80% by 2025, 85% by 2030.",
            "topic": "packaging",
            "related_regulation_id": "Avfallsforskriften-2004",
            "confidence": 0.86,
        },
        {
            "url": "https://www.stortinget.no/no/Saker-og-publikasjoner/Stortingsdokumenter/Meldinger-til-Stortinget/2023-2024/Meld.-St.-25-20232024/",
            "source_id": "stortinget",
            "source_name": "Stortinget — Norwegian Parliament",
            "document_title": "Meld. St. 25 — Norwegian Circular Economy Strategy 2024",
            "snippet": "National circular economy strategy; mandatory EPR for food packaging by 2026.",
            "topic": "waste",
            "related_regulation_id": "CircularEconomy-NO-2024",
            "confidence": 0.85,
        },
    ],

    "trivento-foods": [
        {
            "url": "https://www.gazzettaufficiale.it/eli/gu/2020/12/31/323/sg/pdf",
            "source_id": "gazzetta_ufficiale",
            "source_name": "Gazzetta Ufficiale della Repubblica Italiana",
            "document_title": "Legge di Bilancio 2021 — Plastic Tax (Art. 1, co. 634-658)",
            "snippet": "Italian plastic tax of €0.45/kg on single-use plastic manufactured or imported; postponed to 2024.",
            "topic": "packaging",
            "related_regulation_id": "IT-PlasticTax-2021",
            "confidence": 0.95,
        },
        {
            "url": "https://www.gazzettaufficiale.it/eli/gu/2024/02/01/26/sg/pdf",
            "source_id": "gazzetta_ufficiale",
            "source_name": "Gazzetta Ufficiale della Repubblica Italiana",
            "document_title": "D.Lgs. 18/2024 — CSRD Transposition into Italian Law",
            "snippet": "Italy transposes CSRD: sustainability reporting obligations for large enterprises from FY2024.",
            "topic": "ghg",
            "related_regulation_id": "IT-CSRD-2024",
            "confidence": 0.96,
        },
        {
            "url": "https://www.gazzettaufficiale.it/eli/gu/2022/04/02/77/sg/pdf",
            "source_id": "gazzetta_ufficiale",
            "source_name": "Gazzetta Ufficiale della Repubblica Italiana",
            "document_title": "D.Lgs. 116/2020 — Italian Waste Code Reform",
            "snippet": "Italian implementation of EU Circular Economy Package; extended producer responsibility updates.",
            "topic": "waste",
            "related_regulation_id": "IT-WasteCode-2020",
            "confidence": 0.92,
        },
        {
            "url": "https://www.isprambiente.gov.it/it/pubblicazioni/rapporti/rapporto-rifiuti-urbani-2024",
            "source_id": "ispra",
            "source_name": "ISPRA environmental agency",
            "document_title": "ISPRA Municipal Waste Report 2024 — Packaging Recycling Performance",
            "snippet": "Italy achieved 73% packaging recycling rate in 2023; targets updated to align with PPWR.",
            "topic": "packaging",
            "related_regulation_id": "PPWR-2025",
            "confidence": 0.88,
        },
        {
            "url": "https://www.isprambiente.gov.it/it/banche-dati/banche-dati-folder/acque/le-acque-superficiali",
            "source_id": "ispra",
            "source_name": "ISPRA environmental agency",
            "document_title": "ISPRA Surface Water Quality Monitoring 2024",
            "snippet": "Updated WFD compliance status for Italian waterbodies; effluent discharge standards for food industry.",
            "topic": "water",
            "related_regulation_id": "IT-WFD-2024",
            "confidence": 0.85,
        },
        {
            "url": "https://www.mase.gov.it/comunicati/piano-nazionale-integrato-per-lenergia-e-il-clima-pniec",
            "source_id": "ministero_ambiente",
            "source_name": "Ministero dell'Ambiente",
            "document_title": "PNIEC — Piano Nazionale Integrato per l'Energia e il Clima 2030",
            "snippet": "Italy's integrated energy and climate plan: 65% renewables, 55% GHG reduction targets.",
            "topic": "ghg",
            "related_regulation_id": "IT-PNIEC-2024",
            "confidence": 0.91,
        },
        {
            "url": "https://www.mase.gov.it/comunicati/strategia-nazionale-sviluppo-sostenibile",
            "source_id": "ministero_ambiente",
            "source_name": "Ministero dell'Ambiente",
            "document_title": "Italian National Sustainable Development Strategy 2024",
            "snippet": "Updated sustainability strategy aligning with EU Green Deal and SDGs for industry sector.",
            "topic": "ghg",
            "related_regulation_id": "IT-SNSvS-2024",
            "confidence": 0.87,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022L2464",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSRD — Corporate Sustainability Reporting Directive",
            "snippet": "Italian food companies above EU thresholds must report under ESRS from 2025.",
            "topic": "ghg",
            "related_regulation_id": "CSRD-2022",
            "confidence": 0.97,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32025R0040",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "PPWR — Packaging and Packaging Waste Regulation",
            "snippet": "Mandatory recyclability and recycled content targets affecting Italian pasta and olive oil packaging.",
            "topic": "packaging",
            "related_regulation_id": "PPWR-2025",
            "confidence": 0.96,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024L1760",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSDDD — Corporate Sustainability Due Diligence Directive",
            "snippet": "Italian food companies must conduct value chain due diligence; Ministero Ambiente is competent authority.",
            "topic": "social_human_rights",
            "related_regulation_id": "CSDDD-2024",
            "confidence": 0.95,
        },
        {
            "url": "https://www.gazzettaufficiale.it/eli/gu/2023/12/30/303/sg/pdf",
            "source_id": "gazzetta_ufficiale",
            "source_name": "Gazzetta Ufficiale della Repubblica Italiana",
            "document_title": "Legge di Bilancio 2024 — Green Tax Incentives for Food Industry",
            "snippet": "Tax credits for food manufacturers investing in energy efficiency and circular packaging solutions.",
            "topic": "packaging",
            "related_regulation_id": "IT-GreenIncentives-2024",
            "confidence": 0.86,
        },
        {
            "url": "https://www.isprambiente.gov.it/it/banche-dati/banche-dati-folder/aria/inventario-emissioni-in-atmosfera",
            "source_id": "ispra",
            "source_name": "ISPRA environmental agency",
            "document_title": "ISPRA National GHG Inventory 2024 — Food Processing Sector",
            "snippet": "Food and beverage processing contributes 4.2% of Italian industrial GHG emissions.",
            "topic": "ghg",
            "related_regulation_id": "IT-GHG-Inventory-2024",
            "confidence": 0.84,
        },
    ],

    "terra-verde": [
        {
            "url": "https://dre.pt/dre/legislacao-consolidada/lei/2023-856000",
            "source_id": "dre",
            "source_name": "Diário da República Eletrónico",
            "document_title": "Lei n.º 52/2021 — Adicional sobre emissões de CO2 (Portuguese Carbon Tax)",
            "snippet": "Portugal's carbon tax rate: €50.26/tCO2 in 2025; applies to fuel combustion in food processing.",
            "topic": "ghg",
            "related_regulation_id": "PT-CO2-2021",
            "confidence": 0.94,
        },
        {
            "url": "https://dre.pt/dre/legislacao-consolidada/decreto-lei/2023-802000",
            "source_id": "dre",
            "source_name": "Diário da República Eletrónico",
            "document_title": "DL n.º 102-D/2020 — Portuguese Waste Management Regime",
            "snippet": "Updated waste regime transposing EU Circular Economy Package; EPR for packaging and organics.",
            "topic": "waste",
            "related_regulation_id": "PT-Waste-2020",
            "confidence": 0.93,
        },
        {
            "url": "https://apambiente.pt/index.php?ref=16&subref=81",
            "source_id": "apa",
            "source_name": "Agência Portuguesa do Ambiente",
            "document_title": "APA Environmental Impact Assessment Guide for Food Industry",
            "snippet": "EIA screening thresholds for food processing expansions; water abstraction permit requirements.",
            "topic": "water",
            "related_regulation_id": "PT-AIA-2013",
            "confidence": 0.88,
        },
        {
            "url": "https://apambiente.pt/index.php?ref=16&subref=86",
            "source_id": "apa",
            "source_name": "Agência Portuguesa do Ambiente",
            "document_title": "APA Water Abstraction and Discharge Permits — Agro-food Sector",
            "snippet": "Licensing requirements for water use above 100 m³/day; online permit renewal deadlines.",
            "topic": "water",
            "related_regulation_id": "PT-Water-Permits-2024",
            "confidence": 0.87,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022L2464",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSRD — Corporate Sustainability Reporting Directive",
            "snippet": "Portuguese organic food companies above thresholds must report from FY2025.",
            "topic": "ghg",
            "related_regulation_id": "CSRD-2022",
            "confidence": 0.96,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32025R0040",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "PPWR — Packaging and Packaging Waste Regulation",
            "snippet": "Organic juice and vegetable packaging must meet PPWR recyclability requirements from 2028.",
            "topic": "packaging",
            "related_regulation_id": "PPWR-2025",
            "confidence": 0.95,
        },
        {
            "url": "https://dre.pt/dre/legislacao-consolidada/decreto-lei/2022-760000",
            "source_id": "dre",
            "source_name": "Diário da República Eletrónico",
            "document_title": "DL n.º 79/2022 — Portuguese Organic Waste and Biowaste Regulation",
            "snippet": "Mandatory separate collection of organic waste for food processors above 50 tonnes/year.",
            "topic": "waste",
            "related_regulation_id": "PT-Biowaste-2022",
            "confidence": 0.90,
        },
        {
            "url": "https://apambiente.pt/index.php?ref=16&subref=82",
            "source_id": "apa",
            "source_name": "Agência Portuguesa do Ambiente",
            "document_title": "APA EMAS Registration for Portuguese Agro-food Companies",
            "snippet": "EMAS registration reduces permit fees by 25%; simplified reporting for verified sites.",
            "topic": "ghg",
            "related_regulation_id": "EMAS-PT-2024",
            "confidence": 0.83,
        },
        {
            "url": "https://dre.pt/dre/legislacao-consolidada/resolucao-conselho-ministros/2021-836000",
            "source_id": "dre",
            "source_name": "Diário da República Eletrónico",
            "document_title": "RCM n.º 107/2019 — Portuguese Roadmap for Carbon Neutrality 2050",
            "snippet": "Industry sector GHG reduction pathway; food and agriculture -33% by 2030 vs 2005.",
            "topic": "ghg",
            "related_regulation_id": "PT-RNC2050",
            "confidence": 0.89,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024L1760",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSDDD — Corporate Sustainability Due Diligence Directive",
            "snippet": "Portuguese agro-food companies in scope must map and address supply chain human rights risks.",
            "topic": "social_human_rights",
            "related_regulation_id": "CSDDD-2024",
            "confidence": 0.93,
        },
    ],

    "brosel-backwaren": [
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32025R0040",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "PPWR — Packaging and Packaging Waste Regulation 2025/40",
            "snippet": "Bakery and pastry packaging must achieve 50% recycled content by 2030 under PPWR.",
            "topic": "packaging",
            "related_regulation_id": "PPWR-2025",
            "confidence": 0.97,
        },
        {
            "url": "https://www.recht.bund.de/bgbl/1/2021/S2959/regelungstext.pdf",
            "source_id": "bgbl",
            "source_name": "Bundesgesetzblatt",
            "document_title": "VerpackDG 2019 — Verpackungsgesetz (Packaging Act) with 2024 amendments",
            "snippet": "Updated EPR obligations for German bakery packaging; LUCID registration mandatory.",
            "topic": "packaging",
            "related_regulation_id": "VerpackDG-2019",
            "confidence": 0.95,
        },
        {
            "url": "https://www.recht.bund.de/bgbl/1/2021/S2959/regelungstext.pdf",
            "source_id": "bgbl",
            "source_name": "Bundesgesetzblatt",
            "document_title": "LkSG — Supply Chain Due Diligence Act (applies from 2024 to 1,000+ employees)",
            "snippet": "Brosel Backwaren must implement risk-based supply chain monitoring if headcount exceeds 1,000.",
            "topic": "social_human_rights",
            "related_regulation_id": "LkSG-2021",
            "confidence": 0.93,
        },
        {
            "url": "https://www.bmuv.de/themen/klimaschutz/klimaschutzgesetz",
            "source_id": "bmuv",
            "source_name": "BMUV/UBA",
            "document_title": "Bundes-Klimaschutzgesetz (KSG) — Federal Climate Protection Act",
            "snippet": "Sector budgets for German industry; bakery sector must reduce GHG 40% by 2030.",
            "topic": "ghg",
            "related_regulation_id": "KSG-2021",
            "confidence": 0.95,
        },
        {
            "url": "https://www.bmuv.de/themen/ressourceneffizienz",
            "source_id": "bmuv",
            "source_name": "BMUV/UBA",
            "document_title": "ProgRess III — German Resource Efficiency Programme",
            "snippet": "Mandatory resource efficiency audits for food processing companies above 250 employees.",
            "topic": "waste",
            "related_regulation_id": "ProgRess-III",
            "confidence": 0.87,
        },
        {
            "url": "https://www.bafa.de/DE/Themen/Aussenwirtschaft_Investitionskontrolle/Lieferkettensorgfaltspflichtengesetz/lksg_node.html",
            "source_id": "bafa",
            "source_name": "BAFA",
            "document_title": "BAFA LkSG Compliance Framework — Food and Bakery Sector",
            "snippet": "BAFA sector guidance for food manufacturers; wheat and sugar supply chain risk focus.",
            "topic": "social_human_rights",
            "related_regulation_id": "LkSG-2021",
            "confidence": 0.88,
        },
        {
            "url": "https://www.zsvr.de/ZSVR/DE/Aufgaben/Verpackungsregister/LUCID/lucid_node.html",
            "source_id": "zsvr",
            "source_name": "ZSVR/LUCID",
            "document_title": "LUCID Packaging Register — Mandatory Registration",
            "snippet": "All bakery packaging producers must register in LUCID; annual system participation fees apply.",
            "topic": "packaging",
            "related_regulation_id": "VerpackDG-2019",
            "confidence": 0.93,
        },
        {
            "url": "https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=20009209",
            "source_id": "ris",
            "source_name": "Rechtsinformationssystem Austria",
            "document_title": "EAG — Erneuerbaren-Ausbau-Gesetz (Austrian Renewable Energy Act)",
            "snippet": "Austrian RES expansion targets; PPAs and industrial self-consumption frameworks for manufacturers.",
            "topic": "ghg",
            "related_regulation_id": "AT-EAG-2021",
            "confidence": 0.90,
        },
        {
            "url": "https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=20007045",
            "source_id": "ris",
            "source_name": "Rechtsinformationssystem Austria",
            "document_title": "Austrian Klimaschutzgesetz — Climate Protection Act",
            "snippet": "Vienna Pastries site must comply with Austrian sector GHG budget for food manufacturing.",
            "topic": "ghg",
            "related_regulation_id": "AT-KSG-2011",
            "confidence": 0.89,
        },
        {
            "url": "https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=10010070",
            "source_id": "ris",
            "source_name": "Rechtsinformationssystem Austria",
            "document_title": "Austrian Abfallwirtschaftsgesetz (AWG) — Waste Management Act",
            "snippet": "Austrian waste obligations for food manufacturers; biowaste separation mandatory from 2025.",
            "topic": "waste",
            "related_regulation_id": "AT-AWG-2002",
            "confidence": 0.91,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022L2464",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSRD — Corporate Sustainability Reporting Directive",
            "snippet": "Brösel Backwaren GmbH meets CSRD scope thresholds; reporting mandatory from FY2025.",
            "topic": "ghg",
            "related_regulation_id": "CSRD-2022",
            "confidence": 0.97,
        },
        {
            "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024L1760",
            "source_id": "eur_lex",
            "source_name": "EUR-Lex",
            "document_title": "CSDDD — Corporate Sustainability Due Diligence Directive",
            "snippet": "German and Austrian operations must conduct grain and dairy supply chain due diligence.",
            "topic": "social_human_rights",
            "related_regulation_id": "CSDDD-2024",
            "confidence": 0.94,
        },
        {
            "url": "https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=10020386",
            "source_id": "ris",
            "source_name": "Rechtsinformationssystem Austria",
            "document_title": "Austrian Verpackungsverordnung — Packaging Ordinance (amended 2024)",
            "snippet": "Vienna site packaging obligations: 80% recycling rate for paper/cardboard bakery packaging.",
            "topic": "packaging",
            "related_regulation_id": "AT-VerpackV-2024",
            "confidence": 0.90,
        },
    ],
}


def main():
    agent = SourceScoutAgent()
    totals = {}

    for client_id, records in SEEDS.items():
        print(f"\nSeeding {client_id} ({len(records)} records)...")
        urls = [r["url"] for r in records]
        created = []

        for record in records:
            url = record["url"]
            meta = {k: v for k, v in record.items() if k != "url"}
            result = agent.run({"client_id": client_id, "urls": [url], "metadata": meta})
            created.extend(result["evidence_ids"])

        totals[client_id] = len(created)
        print(f"  Created: {len(created)} evidence records")

    print("\nSeed complete:")
    for client_id, count in totals.items():
        print(f"  {client_id}: {count}")
    print(f"  Total: {sum(totals.values())}")


if __name__ == "__main__":
    main()
